### ISSUE TITLE
the huge lack of privacy & cybersecurity tools in dart

### ISSUE THREAD

**Issue by lucmichalski** [codenashwan/subKiller#1]
Hi @codenashwan  ,

Hope you are all well ! and i wish all the best for this new year !

I work in cybersec and as looking for tools in dart and I found your great project [subKiller](https://github.com/codenashwan/subKiller) :-)

After a couple of researches, the only interesting I found was https://github.com/Codemachine1/Universal-Git-Secret-Finder

And i was surprised that nobody port the Sherlock project: https://github.com/sherlock-project/sherlock

What do think ?

Thanks for any insights or inputs on that situation :-)

Cheers,
Luc

**Comment by codenashwan** [comment]
hello @lucmichalski  

I'm so happy, you've done a good job. I hope you keep :)
